//// Generated by protoc-gen-gleam. DO NOT EDIT.
////
//// Source: aegis/scan/v1/scan.proto
////
//// Proto package: aegis.scan.v1

import gleam_protobuf/wire
import gleam/list

pub type ScanMode {
  ScanModeUnspecified
  ScanModeUrl
  ScanModeRepo
  ScanModeHost
  ScanModeContainer
}

pub fn scan_mode_to_int(v: ScanMode) -> Int {
  case v {
    ScanModeUnspecified -> 0
    ScanModeUrl -> 1
    ScanModeRepo -> 2
    ScanModeHost -> 3
    ScanModeContainer -> 4
  }
}

pub fn scan_mode_from_int(i: Int) -> Result(ScanMode, wire.DecodeError) {
  case i {
    0 -> Ok(ScanModeUnspecified)
    1 -> Ok(ScanModeUrl)
    2 -> Ok(ScanModeRepo)
    3 -> Ok(ScanModeHost)
    4 -> Ok(ScanModeContainer)
    v -> Error(wire.UnknownEnumValue("ScanMode", v))
  }
}

pub fn scan_mode_to_string(v: ScanMode) -> String {
  case v {
    ScanModeUnspecified -> "unspecified"
    ScanModeUrl -> "url"
    ScanModeRepo -> "repo"
    ScanModeHost -> "host"
    ScanModeContainer -> "container"
  }
}

pub type Severity {
  SeverityUnspecified
  SeverityCritical
  SeverityHigh
  SeverityMedium
  SeverityLow
  SeverityInfo
}

pub fn severity_to_int(v: Severity) -> Int {
  case v {
    SeverityUnspecified -> 0
    SeverityCritical -> 1
    SeverityHigh -> 2
    SeverityMedium -> 3
    SeverityLow -> 4
    SeverityInfo -> 5
  }
}

pub fn severity_from_int(i: Int) -> Result(Severity, wire.DecodeError) {
  case i {
    0 -> Ok(SeverityUnspecified)
    1 -> Ok(SeverityCritical)
    2 -> Ok(SeverityHigh)
    3 -> Ok(SeverityMedium)
    4 -> Ok(SeverityLow)
    5 -> Ok(SeverityInfo)
    v -> Error(wire.UnknownEnumValue("Severity", v))
  }
}

pub fn severity_to_string(v: Severity) -> String {
  case v {
    SeverityUnspecified -> "unspecified"
    SeverityCritical -> "critical"
    SeverityHigh -> "high"
    SeverityMedium -> "medium"
    SeverityLow -> "low"
    SeverityInfo -> "info"
  }
}

pub type LogLevel {
  LogLevelUnspecified
  LogLevelDebug
  LogLevelInfo
  LogLevelWarn
  LogLevelError
}

pub fn log_level_to_int(v: LogLevel) -> Int {
  case v {
    LogLevelUnspecified -> 0
    LogLevelDebug -> 1
    LogLevelInfo -> 2
    LogLevelWarn -> 3
    LogLevelError -> 4
  }
}

pub fn log_level_from_int(i: Int) -> Result(LogLevel, wire.DecodeError) {
  case i {
    0 -> Ok(LogLevelUnspecified)
    1 -> Ok(LogLevelDebug)
    2 -> Ok(LogLevelInfo)
    3 -> Ok(LogLevelWarn)
    4 -> Ok(LogLevelError)
    v -> Error(wire.UnknownEnumValue("LogLevel", v))
  }
}

pub fn log_level_to_string(v: LogLevel) -> String {
  case v {
    LogLevelUnspecified -> "unspecified"
    LogLevelDebug -> "debug"
    LogLevelInfo -> "info"
    LogLevelWarn -> "warn"
    LogLevelError -> "error"
  }
}

pub type Payload {
  StartCommand(ScanStartCommand)
  CancelCommand(ScanCancelCommand)
  Started(ScanStartedEvent)
  Progress(ScanProgressEvent)
  Finding(ScanFindingEvent)
  Log(ScanLogEvent)
  Completed(ScanCompletedEvent)
  Failed(ScanFailedEvent)
}

pub type Envelope {
  Envelope(
    schema_version: Int,
    event_id: String,
    scan_id: String,
    timestamp_ms: Int,
    payload: Payload,
  )
}

const field_envelope_schema_version: Int = 1
const field_envelope_event_id: Int = 2
const field_envelope_scan_id: Int = 3
const field_envelope_timestamp_ms: Int = 4
const oneof_envelope_start_command: Int = 10
const oneof_envelope_cancel_command: Int = 11
const oneof_envelope_started: Int = 20
const oneof_envelope_progress: Int = 21
const oneof_envelope_finding: Int = 22
const oneof_envelope_log: Int = 23
const oneof_envelope_completed: Int = 24
const oneof_envelope_failed: Int = 25

pub fn encode_envelope(msg: Envelope) -> BitArray {
  let Envelope(schema_version, event_id, scan_id, timestamp_ms, payload) = msg
  <<
    wire.encode_int_field(field_envelope_schema_version, schema_version):bits,
    wire.encode_string_field(field_envelope_event_id, event_id):bits,
    wire.encode_string_field(field_envelope_scan_id, scan_id):bits,
    wire.encode_int_field(field_envelope_timestamp_ms, timestamp_ms):bits,
    encode_payload_payload(payload):bits,
  >>
}

fn encode_payload_payload(p: Payload) -> BitArray {
  case p {
    StartCommand(m) -> wire.encode_message_field_always(oneof_envelope_start_command, encode_scan_start_command(m))
    CancelCommand(m) -> wire.encode_message_field_always(oneof_envelope_cancel_command, encode_scan_cancel_command(m))
    Started(m) -> wire.encode_message_field_always(oneof_envelope_started, encode_scan_started_event(m))
    Progress(m) -> wire.encode_message_field_always(oneof_envelope_progress, encode_scan_progress_event(m))
    Finding(m) -> wire.encode_message_field_always(oneof_envelope_finding, encode_scan_finding_event(m))
    Log(m) -> wire.encode_message_field_always(oneof_envelope_log, encode_scan_log_event(m))
    Completed(m) -> wire.encode_message_field_always(oneof_envelope_completed, encode_scan_completed_event(m))
    Failed(m) -> wire.encode_message_field_always(oneof_envelope_failed, encode_scan_failed_event(m))
  }
}

type EnvelopeAcc {
  EnvelopeAcc(
    schema_version: Int,
    event_id: String,
    scan_id: String,
    timestamp_ms: Int,
    payload: Result(Payload, Nil),
  )
}

pub fn decode_envelope(buf: BitArray) -> Result(Envelope, wire.DecodeError) {
  let init = EnvelopeAcc(
    schema_version: 0,
    event_id: "",
    scan_id: "",
    timestamp_ms: 0,
    payload: Error(Nil),
  )
  case decode_fields(buf, init, envelope_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      case acc.payload {
        Error(_) -> Error(wire.MissingPayload)
        Ok(p) ->
          Ok(Envelope(
            schema_version: acc.schema_version,
            event_id: acc.event_id,
            scan_id: acc.scan_id,
            timestamp_ms: acc.timestamp_ms,
            payload: p,
          ))
      }
  }
}

fn envelope_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: EnvelopeAcc,
) -> Result(#(EnvelopeAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_envelope_schema_version ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(EnvelopeAcc(..acc, schema_version: v), r))
      }
    n if n == field_envelope_event_id ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(EnvelopeAcc(..acc, event_id: s), r))
          }
      }
    n if n == field_envelope_scan_id ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(EnvelopeAcc(..acc, scan_id: s), r))
          }
      }
    n if n == field_envelope_timestamp_ms ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(EnvelopeAcc(..acc, timestamp_ms: v), r))
      }
    n if n == oneof_envelope_start_command ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_start_command(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(StartCommand(m))), r))
          }
      }
    n if n == oneof_envelope_cancel_command ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_cancel_command(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(CancelCommand(m))), r))
          }
      }
    n if n == oneof_envelope_started ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_started_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Started(m))), r))
          }
      }
    n if n == oneof_envelope_progress ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_progress_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Progress(m))), r))
          }
      }
    n if n == oneof_envelope_finding ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_finding_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Finding(m))), r))
          }
      }
    n if n == oneof_envelope_log ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_log_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Log(m))), r))
          }
      }
    n if n == oneof_envelope_completed ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_completed_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Completed(m))), r))
          }
      }
    n if n == oneof_envelope_failed ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(body, r)) ->
          case decode_scan_failed_event(body) {
            Error(e) -> Error(e)
            Ok(m) -> Ok(#(EnvelopeAcc(..acc, payload: Ok(Failed(m))), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanStartCommand {
  ScanStartCommand(
    target: String,
    mode: ScanMode,
    tools: List(String),
    project_id: String,
    org_id: String,
  )
}

const field_scan_start_command_target: Int = 1
const field_scan_start_command_mode: Int = 2
const field_scan_start_command_tools: Int = 3
const field_scan_start_command_project_id: Int = 4
const field_scan_start_command_org_id: Int = 5

pub fn encode_scan_start_command(msg: ScanStartCommand) -> BitArray {
  let ScanStartCommand(target, mode, tools, project_id, org_id) = msg
  <<
    wire.encode_string_field(field_scan_start_command_target, target):bits,
    wire.encode_int_field(field_scan_start_command_mode, scan_mode_to_int(mode)):bits,
    wire.encode_repeated_strings(field_scan_start_command_tools, tools):bits,
    wire.encode_string_field(field_scan_start_command_project_id, project_id):bits,
    wire.encode_string_field(field_scan_start_command_org_id, org_id):bits,
  >>
}

type ScanStartCommandAcc {
  ScanStartCommandAcc(
    target: String,
    mode: ScanMode,
    tools: List(String),
    project_id: String,
    org_id: String,
  )
}

pub fn decode_scan_start_command(buf: BitArray) -> Result(ScanStartCommand, wire.DecodeError) {
  let init = ScanStartCommandAcc(
    target: "",
    mode: ScanModeUnspecified,
    tools: [],
    project_id: "",
    org_id: "",
  )
  case decode_fields(buf, init, scan_start_command_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanStartCommand(
        target: acc.target,
        mode: acc.mode,
        tools: list.reverse(acc.tools),
        project_id: acc.project_id,
        org_id: acc.org_id,
      ))
  }
}

fn scan_start_command_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanStartCommandAcc,
) -> Result(#(ScanStartCommandAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_start_command_target ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanStartCommandAcc(..acc, target: s), r))
          }
      }
    n if n == field_scan_start_command_mode ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case scan_mode_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) -> Ok(#(ScanStartCommandAcc(..acc, mode: ev), r))
          }
      }
    n if n == field_scan_start_command_tools ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanStartCommandAcc(..acc, tools: [s, ..acc.tools]), r))
          }
      }
    n if n == field_scan_start_command_project_id ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanStartCommandAcc(..acc, project_id: s), r))
          }
      }
    n if n == field_scan_start_command_org_id ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanStartCommandAcc(..acc, org_id: s), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanCancelCommand {
  ScanCancelCommand
}


pub fn encode_scan_cancel_command(_msg: ScanCancelCommand) -> BitArray {
  <<>>
}

pub fn decode_scan_cancel_command(_buf: BitArray) -> Result(ScanCancelCommand, wire.DecodeError) {
  Ok(ScanCancelCommand)
}

pub type ScanStartedEvent {
  ScanStartedEvent
}


pub fn encode_scan_started_event(_msg: ScanStartedEvent) -> BitArray {
  <<>>
}

pub fn decode_scan_started_event(_buf: BitArray) -> Result(ScanStartedEvent, wire.DecodeError) {
  Ok(ScanStartedEvent)
}

pub type ScanProgressEvent {
  ScanProgressEvent(
    phase: String,
    progress: Float,
    message: String,
  )
}

const field_scan_progress_event_phase: Int = 1
const field_scan_progress_event_progress: Int = 2
const field_scan_progress_event_message: Int = 3

pub fn encode_scan_progress_event(msg: ScanProgressEvent) -> BitArray {
  let ScanProgressEvent(phase, progress, message) = msg
  <<
    wire.encode_string_field(field_scan_progress_event_phase, phase):bits,
    wire.encode_float_field(field_scan_progress_event_progress, progress):bits,
    wire.encode_string_field(field_scan_progress_event_message, message):bits,
  >>
}

type ScanProgressEventAcc {
  ScanProgressEventAcc(
    phase: String,
    progress: Float,
    message: String,
  )
}

pub fn decode_scan_progress_event(buf: BitArray) -> Result(ScanProgressEvent, wire.DecodeError) {
  let init = ScanProgressEventAcc(
    phase: "",
    progress: 0.0,
    message: "",
  )
  case decode_fields(buf, init, scan_progress_event_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanProgressEvent(
        phase: acc.phase,
        progress: acc.progress,
        message: acc.message,
      ))
  }
}

fn scan_progress_event_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanProgressEventAcc,
) -> Result(#(ScanProgressEventAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_progress_event_phase ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanProgressEventAcc(..acc, phase: s), r))
          }
      }
    n if n == field_scan_progress_event_progress ->
      case wire.decode_float32(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(ScanProgressEventAcc(..acc, progress: v), r))
      }
    n if n == field_scan_progress_event_message ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanProgressEventAcc(..acc, message: s), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanFindingEvent {
  ScanFindingEvent(
    severity: Severity,
    category: String,
    title: String,
    description: String,
    evidence: String,
    endpoint: String,
    tool: String,
  )
}

const field_scan_finding_event_severity: Int = 1
const field_scan_finding_event_category: Int = 2
const field_scan_finding_event_title: Int = 3
const field_scan_finding_event_description: Int = 4
const field_scan_finding_event_evidence: Int = 5
const field_scan_finding_event_endpoint: Int = 6
const field_scan_finding_event_tool: Int = 7

pub fn encode_scan_finding_event(msg: ScanFindingEvent) -> BitArray {
  let ScanFindingEvent(severity, category, title, description, evidence, endpoint, tool) = msg
  <<
    wire.encode_int_field(field_scan_finding_event_severity, severity_to_int(severity)):bits,
    wire.encode_string_field(field_scan_finding_event_category, category):bits,
    wire.encode_string_field(field_scan_finding_event_title, title):bits,
    wire.encode_string_field(field_scan_finding_event_description, description):bits,
    wire.encode_string_field(field_scan_finding_event_evidence, evidence):bits,
    wire.encode_string_field(field_scan_finding_event_endpoint, endpoint):bits,
    wire.encode_string_field(field_scan_finding_event_tool, tool):bits,
  >>
}

type ScanFindingEventAcc {
  ScanFindingEventAcc(
    severity: Severity,
    category: String,
    title: String,
    description: String,
    evidence: String,
    endpoint: String,
    tool: String,
  )
}

pub fn decode_scan_finding_event(buf: BitArray) -> Result(ScanFindingEvent, wire.DecodeError) {
  let init = ScanFindingEventAcc(
    severity: SeverityUnspecified,
    category: "",
    title: "",
    description: "",
    evidence: "",
    endpoint: "",
    tool: "",
  )
  case decode_fields(buf, init, scan_finding_event_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanFindingEvent(
        severity: acc.severity,
        category: acc.category,
        title: acc.title,
        description: acc.description,
        evidence: acc.evidence,
        endpoint: acc.endpoint,
        tool: acc.tool,
      ))
  }
}

fn scan_finding_event_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanFindingEventAcc,
) -> Result(#(ScanFindingEventAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_finding_event_severity ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case severity_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) -> Ok(#(ScanFindingEventAcc(..acc, severity: ev), r))
          }
      }
    n if n == field_scan_finding_event_category ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, category: s), r))
          }
      }
    n if n == field_scan_finding_event_title ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, title: s), r))
          }
      }
    n if n == field_scan_finding_event_description ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, description: s), r))
          }
      }
    n if n == field_scan_finding_event_evidence ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, evidence: s), r))
          }
      }
    n if n == field_scan_finding_event_endpoint ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, endpoint: s), r))
          }
      }
    n if n == field_scan_finding_event_tool ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFindingEventAcc(..acc, tool: s), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanLogEvent {
  ScanLogEvent(
    level: LogLevel,
    message: String,
    phase: String,
  )
}

const field_scan_log_event_level: Int = 1
const field_scan_log_event_message: Int = 2
const field_scan_log_event_phase: Int = 3

pub fn encode_scan_log_event(msg: ScanLogEvent) -> BitArray {
  let ScanLogEvent(level, message, phase) = msg
  <<
    wire.encode_int_field(field_scan_log_event_level, log_level_to_int(level)):bits,
    wire.encode_string_field(field_scan_log_event_message, message):bits,
    wire.encode_string_field(field_scan_log_event_phase, phase):bits,
  >>
}

type ScanLogEventAcc {
  ScanLogEventAcc(
    level: LogLevel,
    message: String,
    phase: String,
  )
}

pub fn decode_scan_log_event(buf: BitArray) -> Result(ScanLogEvent, wire.DecodeError) {
  let init = ScanLogEventAcc(
    level: LogLevelUnspecified,
    message: "",
    phase: "",
  )
  case decode_fields(buf, init, scan_log_event_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanLogEvent(
        level: acc.level,
        message: acc.message,
        phase: acc.phase,
      ))
  }
}

fn scan_log_event_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanLogEventAcc,
) -> Result(#(ScanLogEventAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_log_event_level ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) ->
          case log_level_from_int(v) {
            Error(e) -> Error(e)
            Ok(ev) -> Ok(#(ScanLogEventAcc(..acc, level: ev), r))
          }
      }
    n if n == field_scan_log_event_message ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanLogEventAcc(..acc, message: s), r))
          }
      }
    n if n == field_scan_log_event_phase ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanLogEventAcc(..acc, phase: s), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanCompletedEvent {
  ScanCompletedEvent(
    finding_count: Int,
    duration_ms: Int,
  )
}

const field_scan_completed_event_finding_count: Int = 1
const field_scan_completed_event_duration_ms: Int = 2

pub fn encode_scan_completed_event(msg: ScanCompletedEvent) -> BitArray {
  let ScanCompletedEvent(finding_count, duration_ms) = msg
  <<
    wire.encode_int_field(field_scan_completed_event_finding_count, finding_count):bits,
    wire.encode_int_field(field_scan_completed_event_duration_ms, duration_ms):bits,
  >>
}

type ScanCompletedEventAcc {
  ScanCompletedEventAcc(
    finding_count: Int,
    duration_ms: Int,
  )
}

pub fn decode_scan_completed_event(buf: BitArray) -> Result(ScanCompletedEvent, wire.DecodeError) {
  let init = ScanCompletedEventAcc(
    finding_count: 0,
    duration_ms: 0,
  )
  case decode_fields(buf, init, scan_completed_event_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanCompletedEvent(
        finding_count: acc.finding_count,
        duration_ms: acc.duration_ms,
      ))
  }
}

fn scan_completed_event_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanCompletedEventAcc,
) -> Result(#(ScanCompletedEventAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_completed_event_finding_count ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(ScanCompletedEventAcc(..acc, finding_count: v), r))
      }
    n if n == field_scan_completed_event_duration_ms ->
      case wire.decode_varint(rest) {
        Error(e) -> Error(e)
        Ok(#(v, r)) -> Ok(#(ScanCompletedEventAcc(..acc, duration_ms: v), r))
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

pub type ScanFailedEvent {
  ScanFailedEvent(
    reason: String,
    phase: String,
  )
}

const field_scan_failed_event_reason: Int = 1
const field_scan_failed_event_phase: Int = 2

pub fn encode_scan_failed_event(msg: ScanFailedEvent) -> BitArray {
  let ScanFailedEvent(reason, phase) = msg
  <<
    wire.encode_string_field(field_scan_failed_event_reason, reason):bits,
    wire.encode_string_field(field_scan_failed_event_phase, phase):bits,
  >>
}

type ScanFailedEventAcc {
  ScanFailedEventAcc(
    reason: String,
    phase: String,
  )
}

pub fn decode_scan_failed_event(buf: BitArray) -> Result(ScanFailedEvent, wire.DecodeError) {
  let init = ScanFailedEventAcc(
    reason: "",
    phase: "",
  )
  case decode_fields(buf, init, scan_failed_event_field_handler) {
    Error(e) -> Error(e)
    Ok(acc) ->
      Ok(ScanFailedEvent(
        reason: acc.reason,
        phase: acc.phase,
      ))
  }
}

fn scan_failed_event_field_handler(
  field_number: Int,
  wire_type: Int,
  rest: BitArray,
  acc: ScanFailedEventAcc,
) -> Result(#(ScanFailedEventAcc, BitArray), wire.DecodeError) {
  case field_number {
    n if n == field_scan_failed_event_reason ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFailedEventAcc(..acc, reason: s), r))
          }
      }
    n if n == field_scan_failed_event_phase ->
      case wire.decode_len_delimited(rest) {
        Error(e) -> Error(e)
        Ok(#(bytes, r)) ->
          case wire.decode_string(bytes) {
            Error(e) -> Error(e)
            Ok(s) -> Ok(#(ScanFailedEventAcc(..acc, phase: s), r))
          }
      }
    _ ->
      case wire.skip_field(rest, wire_type) {
        Ok(r) -> Ok(#(acc, r))
        Error(e) -> Error(e)
      }
  }
}

// --- Shared decode helpers -------------------------------------------

fn decode_fields(
  buf: BitArray,
  acc: a,
  handler: fn(Int, Int, BitArray, a) ->
    Result(#(a, BitArray), wire.DecodeError),
) -> Result(a, wire.DecodeError) {
  case buf {
    <<>> -> Ok(acc)
    _ ->
      case wire.decode_tag(buf) {
        Error(e) -> Error(e)
        Ok(#(field_number, wire_type, rest)) ->
          case handler(field_number, wire_type, rest, acc) {
            Error(e) -> Error(e)
            Ok(#(new_acc, new_rest)) ->
              decode_fields(new_rest, new_acc, handler)
          }
      }
  }
}

