// Package generator produces Gleam source files from proto descriptors.
package generator

import (
	"fmt"
	"strings"

	gleamfmt "github.com/qwexvf/protoc-gen-gleam/internal/gleam"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// GenerateFile emits one .gleam file per .proto file.
func GenerateFile(gen *protogen.Plugin, file *protogen.File, packagePrefix string) error {
	moduleName := gleamfmt.ModuleName(file.Desc.Path(), packagePrefix)

	outPath := moduleName + ".gleam"
	g := gen.NewGeneratedFile(outPath, file.GoImportPath)

	ctx := &genContext{
		w:             &writer{buf: g},
		gen:           gen,
		file:          file,
		packagePrefix: packagePrefix,
		thisModule:    moduleName,
		imports:       make(map[string]bool),
	}

	ctx.w.P("//// Generated by protoc-gen-gleam. DO NOT EDIT.")
	ctx.w.P("////")
	ctx.w.P("//// Source: %s", file.Desc.Path())
	ctx.w.P("////")
	ctx.w.P("//// Proto package: %s", file.Desc.Package())
	ctx.w.P("")

	// Scan for needed imports before generating code.
	scanImports(ctx, file)

	ctx.w.P("import gleam_protobuf/wire")
	if ctx.imports["gleam/list"] {
		ctx.w.P("import gleam/list")
	}
	if ctx.imports["gleam/dict"] {
		ctx.w.P("import gleam/dict")
	}
	// Cross-file imports.
	for mod := range ctx.imports {
		if strings.HasPrefix(mod, "gleam/") {
			continue
		}
		ctx.w.P("import %s", mod)
	}
	ctx.w.P("")

	// Generate enums.
	for _, enum := range file.Enums {
		generateEnum(ctx.w, enum)
	}

	// Generate messages (skip synthetic map entry messages).
	for _, msg := range file.Messages {
		if msg.Desc.IsMapEntry() {
			continue
		}
		if err := generateMessage(ctx, msg); err != nil {
			return err
		}
	}

	// Emit the shared decode_fields helper at the bottom.
	if hasDecodableMessages(file) {
		generateDecodeFieldsHelper(ctx.w)
	}

	return nil
}

// genContext carries state through code generation.
type genContext struct {
	w             *writer
	gen           *protogen.Plugin
	file          *protogen.File
	packagePrefix string
	thisModule    string
	imports       map[string]bool
}

func hasDecodableMessages(file *protogen.File) bool {
	for _, msg := range file.Messages {
		if !msg.Desc.IsMapEntry() {
			return true
		}
	}
	return false
}

func scanImports(ctx *genContext, file *protogen.File) {
	for _, msg := range file.Messages {
		scanMessageImports(ctx, msg)
	}
}

func scanMessageImports(ctx *genContext, msg *protogen.Message) {
	for _, f := range msg.Fields {
		if f.Desc.IsList() || f.Desc.IsMap() {
			ctx.imports["gleam/list"] = true
		}
		if f.Desc.IsMap() {
			ctx.imports["gleam/dict"] = true
			ctx.imports["gleam/list"] = true
		}
		// bytes fields don't need gleam/bit_array — wire module handles encoding.
		// Cross-file type references.
		if f.Desc.Kind() == protoreflect.MessageKind && f.Message != nil && !f.Desc.IsMap() {
			otherFile := f.Message.Desc.ParentFile()
			if otherFile != nil && otherFile.Path() != ctx.file.Desc.Path() {
				mod := gleamfmt.ModuleName(string(otherFile.Path()), ctx.packagePrefix)
				ctx.imports[mod] = true
			}
		}
		if f.Desc.Kind() == protoreflect.EnumKind && f.Enum != nil {
			otherFile := f.Enum.Desc.ParentFile()
			if otherFile != nil && otherFile.Path() != ctx.file.Desc.Path() {
				mod := gleamfmt.ModuleName(string(otherFile.Path()), ctx.packagePrefix)
				ctx.imports[mod] = true
			}
		}
	}
	for _, nested := range msg.Messages {
		scanMessageImports(ctx, nested)
	}
}

// generateEnum emits a Gleam enum type + to_int/from_int/to_string.
func generateEnum(w *writer, enum *protogen.Enum) {
	typeName := gleamfmt.TypeName(string(enum.Desc.Name()))

	w.P("pub type %s {", typeName)
	for _, v := range enum.Values {
		variantName := gleamfmt.EnumVariantName(string(enum.Desc.Name()), string(v.Desc.Name()))
		w.P("  %s", variantName)
	}
	w.P("}")
	w.P("")

	fnName := gleamfmt.ToSnakeCase(string(enum.Desc.Name()))
	w.P("pub fn %s_to_int(v: %s) -> Int {", fnName, typeName)
	w.P("  case v {")
	for _, v := range enum.Values {
		variantName := gleamfmt.EnumVariantName(string(enum.Desc.Name()), string(v.Desc.Name()))
		w.P("    %s -> %d", variantName, v.Desc.Number())
	}
	w.P("  }")
	w.P("}")
	w.P("")

	w.P("pub fn %s_from_int(i: Int) -> Result(%s, wire.DecodeError) {", fnName, typeName)
	w.P("  case i {")
	for _, v := range enum.Values {
		variantName := gleamfmt.EnumVariantName(string(enum.Desc.Name()), string(v.Desc.Name()))
		w.P("    %d -> Ok(%s)", v.Desc.Number(), variantName)
	}
	w.P("    v -> Error(wire.UnknownEnumValue(\"%s\", v))", typeName)
	w.P("  }")
	w.P("}")
	w.P("")

	w.P("pub fn %s_to_string(v: %s) -> String {", fnName, typeName)
	w.P("  case v {")
	for _, v := range enum.Values {
		variantName := gleamfmt.EnumVariantName(string(enum.Desc.Name()), string(v.Desc.Name()))
		strVal := gleamfmt.EnumToStringValue(string(enum.Desc.Name()), string(v.Desc.Name()))
		w.P("    %s -> \"%s\"", variantName, strVal)
	}
	w.P("  }")
	w.P("}")
	w.P("")
}

// generateMessage emits type + oneof sum type + encoder + decoder.
func generateMessage(ctx *genContext, msg *protogen.Message) error {
	// Skip synthetic map entry messages — they're handled inline.
	if msg.Desc.IsMapEntry() {
		return nil
	}

	typeName := fullTypeName(msg)

	// Nested enums.
	for _, enum := range msg.Enums {
		generateEnum(ctx.w, enum)
	}

	// Nested messages (skip map entries).
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		if err := generateMessage(ctx, nested); err != nil {
			return err
		}
	}

	// Collect oneof groups (skip synthetic oneofs from proto3 optional).
	oneofs := collectOneofs(msg)

	// Generate oneof sum types.
	for _, oo := range oneofs {
		generateOneofType(ctx, oo)
	}

	// Message record type.
	regular := regularFields(msg)
	if len(regular) == 0 && len(oneofs) == 0 {
		ctx.w.P("pub type %s {", typeName)
		ctx.w.P("  %s", typeName)
		ctx.w.P("}")
	} else {
		ctx.w.P("pub type %s {", typeName)
		ctx.w.P("  %s(", typeName)
		fields := make([]string, 0)
		for _, f := range regular {
			fields = append(fields, fmt.Sprintf("    %s: %s", gleamfmt.FieldName(string(f.Desc.Name())), gleamFieldType(ctx, f)))
		}
		for _, oo := range oneofs {
			fields = append(fields, fmt.Sprintf("    %s: %s", gleamfmt.FieldName(string(oo.Desc.Name())), gleamfmt.ToPascalCase(string(oo.Desc.Name()))))
		}
		ctx.w.P("%s,", strings.Join(fields, ",\n"))
		ctx.w.P("  )")
		ctx.w.P("}")
	}
	ctx.w.P("")

	generateFieldConstants(ctx.w, msg, typeName)
	generateEncoder(ctx, msg, typeName, oneofs)
	generateDecoder(ctx, msg, typeName, oneofs)

	return nil
}

// fullTypeName returns the Gleam type name for a message, handling nesting.
// E.g. message Outer { message Inner {} } -> "OuterInner".
func fullTypeName(msg *protogen.Message) string {
	parts := []string{string(msg.Desc.Name())}
	parent := msg.Desc.Parent()
	for {
		if pm, ok := parent.(protoreflect.MessageDescriptor); ok {
			parts = append([]string{string(pm.Name())}, parts...)
			parent = pm.Parent()
		} else {
			break
		}
	}
	return strings.Join(parts, "")
}

// Well-known type mappings: proto full name -> (Gleam type, module alias).
var wellKnownTypes = map[string]struct {
	gleamType string
	module    string
}{
	"google.protobuf.Timestamp":   {"well_known.Timestamp", "gleam_protobuf/well_known"},
	"google.protobuf.Duration":    {"well_known.Duration", "gleam_protobuf/well_known"},
	"google.protobuf.Empty":       {"well_known.Empty", "gleam_protobuf/well_known"},
	"google.protobuf.StringValue": {"well_known.StringValue", "gleam_protobuf/well_known"},
	"google.protobuf.Int64Value":  {"well_known.Int64Value", "gleam_protobuf/well_known"},
	"google.protobuf.BoolValue":   {"well_known.BoolValue", "gleam_protobuf/well_known"},
	"google.protobuf.FloatValue":  {"well_known.FloatValue", "gleam_protobuf/well_known"},
	"google.protobuf.DoubleValue": {"well_known.DoubleValue", "gleam_protobuf/well_known"},
	"google.protobuf.BytesValue":  {"well_known.BytesValue", "gleam_protobuf/well_known"},
}

// isWellKnownMessage returns the Gleam type name if the message is a
// well-known type, or "" otherwise.
func isWellKnownMessage(msg *protogen.Message) (gleamType string, ok bool) {
	fullName := string(msg.Desc.FullName())
	if wk, found := wellKnownTypes[fullName]; found {
		return wk.gleamType, true
	}
	return "", false
}

// fullTypeRef returns a type reference that may be qualified with a module
// prefix if the type comes from another file or is a well-known type.
func fullTypeRef(ctx *genContext, f *protogen.Field) string {
	if f.Message != nil {
		if wkType, ok := isWellKnownMessage(f.Message); ok {
			ctx.imports["gleam_protobuf/well_known"] = true
			return wkType
		}
		otherFile := f.Message.Desc.ParentFile()
		if otherFile != nil && otherFile.Path() != ctx.file.Desc.Path() {
			mod := gleamfmt.ModuleName(string(otherFile.Path()), ctx.packagePrefix)
			shortMod := mod
			if idx := strings.LastIndex(mod, "/"); idx >= 0 {
				shortMod = mod[idx+1:]
			}
			return shortMod + "." + fullMsgTypeName(f.Message)
		}
		return fullMsgTypeName(f.Message)
	}
	if f.Enum != nil {
		otherFile := f.Enum.Desc.ParentFile()
		if otherFile != nil && otherFile.Path() != ctx.file.Desc.Path() {
			mod := gleamfmt.ModuleName(string(otherFile.Path()), ctx.packagePrefix)
			shortMod := mod
			if idx := strings.LastIndex(mod, "/"); idx >= 0 {
				shortMod = mod[idx+1:]
			}
			return shortMod + "." + gleamfmt.TypeName(string(f.Enum.Desc.Name()))
		}
		return gleamfmt.TypeName(string(f.Enum.Desc.Name()))
	}
	return "Dynamic"
}

// fullMsgTypeName is an alias for fullTypeName (kept for readability at call sites).
func fullMsgTypeName(msg *protogen.Message) string {
	return fullTypeName(msg)
}

// oneofInfo collects info about a oneof group.
type oneofInfo struct {
	Desc   protoreflect.OneofDescriptor
	Fields []*protogen.Field
}

func collectOneofs(msg *protogen.Message) []oneofInfo {
	if msg.Desc.Oneofs().Len() == 0 {
		return nil
	}

	seen := make(map[string]*oneofInfo)
	var order []string

	for _, f := range msg.Fields {
		oo := f.Desc.ContainingOneof()
		if oo == nil || oo.IsSynthetic() {
			continue
		}
		name := string(oo.Name())
		if info, ok := seen[name]; ok {
			info.Fields = append(info.Fields, f)
		} else {
			seen[name] = &oneofInfo{Desc: oo, Fields: []*protogen.Field{f}}
			order = append(order, name)
		}
	}

	result := make([]oneofInfo, 0, len(order))
	for _, name := range order {
		result = append(result, *seen[name])
	}
	return result
}

func generateOneofType(ctx *genContext, oo oneofInfo) {
	typeName := gleamfmt.ToPascalCase(string(oo.Desc.Name()))
	ctx.w.P("pub type %s {", typeName)
	for _, f := range oo.Fields {
		variantName := gleamfmt.OneofVariantName(string(f.Desc.Name()))
		variantType := oneofVariantType(ctx, f)
		ctx.w.P("  %s(%s)", variantName, variantType)
	}
	ctx.w.P("}")
	ctx.w.P("")
}

// oneofVariantType returns the Gleam type for a oneof variant.
// Handles both message and scalar variants.
func oneofVariantType(ctx *genContext, f *protogen.Field) string {
	if f.Message != nil {
		return fullTypeRef(ctx, f)
	}
	return gleamScalarType(ctx, f)
}

// regularFields returns fields not part of a real oneof.
// Proto3 optional fields have a synthetic oneof but are treated as regular.
func regularFields(msg *protogen.Message) []*protogen.Field {
	var result []*protogen.Field
	for _, f := range msg.Fields {
		oo := f.Desc.ContainingOneof()
		if oo != nil && !oo.IsSynthetic() {
			continue
		}
		result = append(result, f)
	}
	return result
}

// isOptional returns true if the field uses proto3 explicit optional.
func isOptional(f *protogen.Field) bool {
	return f.Desc.HasOptionalKeyword()
}

// isMap returns true if the field is a map.
func isMap(f *protogen.Field) bool {
	return f.Desc.IsMap()
}

func gleamFieldType(ctx *genContext, f *protogen.Field) string {
	if isMap(f) {
		mapEntry := f.Message
		keyField := mapEntry.Fields[0]
		valField := mapEntry.Fields[1]
		return fmt.Sprintf("dict.Dict(%s, %s)", gleamScalarType(ctx, keyField), gleamScalarType(ctx, valField))
	}
	if f.Desc.IsList() {
		return fmt.Sprintf("List(%s)", gleamScalarType(ctx, f))
	}
	if isOptional(f) {
		return fmt.Sprintf("Result(%s, Nil)", gleamScalarType(ctx, f))
	}
	return gleamScalarType(ctx, f)
}

func gleamScalarType(ctx *genContext, f *protogen.Field) string {
	switch f.Desc.Kind() {
	case protoreflect.StringKind:
		return "String"
	case protoreflect.BoolKind:
		return "Bool"
	case protoreflect.Int32Kind, protoreflect.Int64Kind,
		protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind,
		protoreflect.Fixed32Kind, protoreflect.Fixed64Kind,
		protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind:
		return "Int"
	case protoreflect.FloatKind:
		return "Float"
	case protoreflect.DoubleKind:
		return "Float"
	case protoreflect.BytesKind:
		return "BitArray"
	case protoreflect.EnumKind:
		return fullTypeRef(ctx, f)
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return fullTypeRef(ctx, f)
	default:
		return "Dynamic"
	}
}

func generateFieldConstants(w *writer, msg *protogen.Message, typeName string) {
	prefix := "field_" + gleamfmt.ToSnakeCase(typeName)
	oneofPrefix := "oneof_" + gleamfmt.ToSnakeCase(typeName)
	for _, f := range msg.Fields {
		oo := f.Desc.ContainingOneof()
		if oo != nil && !oo.IsSynthetic() {
			w.P("const %s_%s: Int = %d", oneofPrefix, string(f.Desc.Name()), f.Desc.Number())
		} else {
			w.P("const %s_%s: Int = %d", prefix, string(f.Desc.Name()), f.Desc.Number())
		}
	}
	w.P("")
}

// oneofConstName returns the constant name for a oneof field, scoped by message.
func oneofConstName(typeName string, f *protogen.Field) string {
	return "oneof_" + gleamfmt.ToSnakeCase(typeName) + "_" + string(f.Desc.Name())
}

// writer wraps a generated file for convenient line-oriented output.
type writer struct {
	buf *protogen.GeneratedFile
}

func (w *writer) P(format string, args ...any) {
	if len(args) > 0 {
		fmt.Fprintf(w.buf, format, args...)
	} else {
		fmt.Fprint(w.buf, format)
	}
	fmt.Fprintln(w.buf)
}

// encoderFnName returns the Gleam function name for encoding a message.
func encoderFnName(ctx *genContext, msg *protogen.Message) string {
	// Well-known types have pre-built encoders in the runtime.
	fullName := string(msg.Desc.FullName())
	switch fullName {
	case "google.protobuf.Timestamp":
		return "well_known.encode_timestamp"
	case "google.protobuf.Duration":
		return "well_known.encode_duration"
	case "google.protobuf.Empty":
		return "well_known.encode_empty"
	case "google.protobuf.StringValue":
		return "well_known.encode_string_value"
	case "google.protobuf.Int64Value":
		return "well_known.encode_int64_value"
	case "google.protobuf.BoolValue":
		return "well_known.encode_bool_value"
	case "google.protobuf.FloatValue":
		return "well_known.encode_float_value"
	case "google.protobuf.DoubleValue":
		return "well_known.encode_double_value"
	case "google.protobuf.BytesValue":
		return "well_known.encode_bytes_value"
	}

	if msg.Desc.ParentFile().Path() != ctx.file.Desc.Path() {
		mod := gleamfmt.ModuleName(string(msg.Desc.ParentFile().Path()), ctx.packagePrefix)
		shortMod := mod
		if idx := strings.LastIndex(mod, "/"); idx >= 0 {
			shortMod = mod[idx+1:]
		}
		return shortMod + ".encode_" + gleamfmt.ToSnakeCase(fullMsgTypeName(msg))
	}
	return "encode_" + gleamfmt.ToSnakeCase(fullMsgTypeName(msg))
}

// decoderFnName returns the Gleam function name for decoding a message.
func decoderFnName(ctx *genContext, msg *protogen.Message) string {
	fullName := string(msg.Desc.FullName())
	switch fullName {
	case "google.protobuf.Timestamp":
		return "well_known.decode_timestamp"
	case "google.protobuf.Duration":
		return "well_known.decode_duration"
	case "google.protobuf.Empty":
		return "well_known.decode_empty"
	case "google.protobuf.StringValue":
		return "well_known.decode_string_value"
	case "google.protobuf.Int64Value":
		return "well_known.decode_int64_value"
	case "google.protobuf.BoolValue":
		return "well_known.decode_bool_value"
	case "google.protobuf.FloatValue":
		return "well_known.decode_float_value"
	case "google.protobuf.DoubleValue":
		return "well_known.decode_double_value"
	case "google.protobuf.BytesValue":
		return "well_known.decode_bytes_value"
	}

	if msg.Desc.ParentFile().Path() != ctx.file.Desc.Path() {
		mod := gleamfmt.ModuleName(string(msg.Desc.ParentFile().Path()), ctx.packagePrefix)
		shortMod := mod
		if idx := strings.LastIndex(mod, "/"); idx >= 0 {
			shortMod = mod[idx+1:]
		}
		return shortMod + ".decode_" + gleamfmt.ToSnakeCase(fullMsgTypeName(msg))
	}
	return "decode_" + gleamfmt.ToSnakeCase(fullMsgTypeName(msg))
}

// enumFnPrefix returns the module-qualified enum function prefix.
func enumFnPrefix(ctx *genContext, f *protogen.Field) string {
	prefix := gleamfmt.ToSnakeCase(string(f.Enum.Desc.Name()))
	if f.Enum.Desc.ParentFile().Path() != ctx.file.Desc.Path() {
		mod := gleamfmt.ModuleName(string(f.Enum.Desc.ParentFile().Path()), ctx.packagePrefix)
		shortMod := mod
		if idx := strings.LastIndex(mod, "/"); idx >= 0 {
			shortMod = mod[idx+1:]
		}
		return shortMod + "." + prefix
	}
	return prefix
}
